version: '3'

services:
  db:
    image: postgres:10-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dmd_project
      POSTGRES_DATABASE: dmd_project
      POSTGRES_PASSWORD: dmd_project
    volumes:
      - ./dump_2018-11-26_23-43.sql:/docker-entrypoint-initdb.d/schema_and_data.sql
